name: CI with SonarQube

on:
  push:
    branches: [ main ]

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root

      - name: Run linting with ruff
        run: |
          poetry run ruff check src tests

      - name: Run linting with flake8
        run: |
          poetry run flake8 --ignore=E501,W503 src tests

      - name: Code cyclomatic complixity analysis
        run: |
          poetry run radon cc src -a

      - name: Code duplication check
        run: |
          poetry run pylint --disable=all --enable=duplicate-code src

      - name: Check propagation cost
        run: |
          poetry run pylint --disable=all --enable=design src

      - name: Run tests & generate coverage
        run: |
          poetry run python -m pytest

      - name: Run fuzz-tests & generate coverage
        run: |
          poetry run python -m pytest tests/fuzzing -v --cov=src --cov-config=.fuzz-coveragerc

      - name: Security check with bandit
        run: |
          poetry run bandit -r src --exclude src/ui/.venv

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
